/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlns_da;

import Entity.Deparment;
import Entity.EmpPro;
import Entity.Project;
import Mannager.ManagerDeparment;
import Mannager.ManagerPro;
import Mannager.ManagerPro.Emp;
import java.sql.SQLException;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AnhHieu
 */
public class frAddEmpforPro extends javax.swing.JInternalFrame {

    DefaultTableModel dtm = new DefaultTableModel();
    DefaultTableModel dtm2 = new DefaultTableModel();
    DefaultComboBoxModel<Deparment> modelDepar;
    DefaultComboBoxModel<Project> modelPro;
    DefaultComboBoxModel<Emp> modelEmp;

    String id;

    /**
     * Creates new form frAddEmpforPro
     */
    public frAddEmpforPro() {
        try {
            try {
                initComponents();
                loadDepar();
                setDate();
                loadcboIdE();
                dtm.addColumn("Mã nhân viên");
                dtm.addColumn("Tên nhân viên");
                dtm.addColumn("Chức vụ");
                loadcboPro();
                tblEmp.setModel(dtm);
                dtm2.addColumn("Mã nhân viên");
                dtm2.addColumn("Mã dự án");
                dtm2.addColumn("Ngày Join");
                dtm2.addColumn("Chú thích");
                dtm2.addColumn("Vị trí");
                loadEmPro();
                tblEmpPro.setModel(dtm2);
            } catch (SQLException ex) {
                Logger.getLogger(frAddEmpforPro.class.getName()).log(Level.SEVERE, null, ex);
            }
            loadEmpforPro();
            loadEtofr();
        } catch (SQLException ex) {
            Logger.getLogger(frAddEmpforPro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public frAddEmpforPro(String id) {
        try {
            try {
                initComponents();
                loadDepar();
                setDate();
                loadcboIdE();
                this.id = id;
                dtm.addColumn("Mã nhân viên");
                dtm.addColumn("Tên nhân viên");
                dtm.addColumn("Chức vụ");
                loadcboPro();
                dtm2.addColumn("Mã nhân viên");
                dtm2.addColumn("Mã dự án");
                dtm2.addColumn("Ngày Join");
                dtm2.addColumn("Chú thích");
                dtm2.addColumn("Vị trí");
                tblEmp.setModel(dtm);
               
                loadEmPro();
                tblEmpPro.setModel(dtm2);
            } catch (SQLException ex) {
                Logger.getLogger(frAddEmpforPro.class.getName()).log(Level.SEVERE, null, ex);
            }
            loadEmpforPro();
            loadEtofr();
            setcboPro(id);
        } catch (SQLException ex) {
            Logger.getLogger(frAddEmpforPro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboDep = new javax.swing.JComboBox();
        cboIdEmp = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmp = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cboPro = new javax.swing.JComboBox();
        txtNamePro = new javax.swing.JTextField();
        txtNameEmp = new javax.swing.JTextField();
        txtPsEmp = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEmpPro = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cboRole = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtNote = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        txtDatejoin = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        setTitle("Quản lý dự án");

        jLabel1.setText("Mã nhân viên:");

        jLabel2.setText("Nhân viên ở phòng ban:");

        cboDep.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboDep.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboDepItemStateChanged(evt);
            }
        });

        cboIdEmp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboIdEmp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboIdEmpItemStateChanged(evt);
            }
        });

        jLabel3.setText("Chức vụ:");

        jLabel4.setText("Tên nhân viên:");

        tblEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpMouseClicked(evt);
            }
        });
        tblEmp.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblEmpPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmp);

        jLabel5.setText("Tên dự án:");

        jLabel6.setText("Mã dự án:");

        cboPro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtNamePro.setEnabled(false);

        txtNameEmp.setEnabled(false);

        txtPsEmp.setEnabled(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách nhân viên làm dự án"));

        tblEmpPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEmpPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpProMouseClicked(evt);
            }
        });
        tblEmpPro.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblEmpProPropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(tblEmpPro);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setText("Sửa");
        btnEdit.setEnabled(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnSave.setText("Lưu lại");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setText("Xóa");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel7.setText("Chú thích:");

        jLabel8.setText("Vị trí:");

        cboRole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Member", "Leader" }));

        txtNote.setColumns(20);
        txtNote.setRows(5);
        jScrollPane3.setViewportView(txtNote);

        jLabel9.setText("Ngày join Dự án:");

        txtDatejoin.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNamePro)
                            .addComponent(cboPro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboDep, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboIdEmp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNameEmp)
                            .addComponent(txtPsEmp)
                            .addComponent(cboRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDatejoin, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(11, 11, 11)
                                .addComponent(jScrollPane3))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cboPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtNamePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cboDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cboIdEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNameEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPsEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(cboRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatejoin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnEdit)
                    .addComponent(btnSave)
                    .addComponent(btnDelete)
                    .addComponent(btnReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadEmPro() throws SQLException {

        Project pj = (Project) cboPro.getSelectedItem();
        String n = pj.getId();
        ManagerPro mn = new ManagerPro();
        Vector<EmpPro> ls = new Vector<>();
        ls = mn.getEmpPro(n);
        for (int i = 0; i < ls.size(); i++) {
            EmpPro elementAt = ls.elementAt(i);
            Vector row = new Vector<>();
            row.add(elementAt.getIdEmp());
            row.add(elementAt.getIdPro());
            row.add(elementAt.getDateJoin());
            row.add(elementAt.getContent());
            if (elementAt.getStatus() == 1) {
                row.add("Member");
            } else {
                row.add("Leader");
            }
            dtm2.addRow(row);
        }

    }
    private void cboDepItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboDepItemStateChanged
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        try {

            loadEmpforPro();
            loadcboIdE();
            loadEtofr();
        } catch (SQLException ex) {
            Logger.getLogger(frAddEmpforPro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cboDepItemStateChanged

    private void cboIdEmpItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboIdEmpItemStateChanged
        loadEtofr();
    }//GEN-LAST:event_cboIdEmpItemStateChanged

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            int k = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn thêm nhân viên vào dự án", "Thông báo", JOptionPane.YES_NO_OPTION);

            if (k == 0) {
                Project pj = (Project) cboPro.getSelectedItem();
                String n = pj.getId();
                Emp e = (Emp) cboIdEmp.getSelectedItem();
                String id = e.getId();
                EmpPro ep = new EmpPro();
                ep.setIdEmp(id);
                ep.setIdPro(n);
                ep.setDateJoin(txtDatejoin.getDate());
                ep.setContent(txtNote.getText());
                if (cboRole.getSelectedIndex() == 0) {
                    ep.setStatus(1);
                } else {
                    ep.setStatus(1);
                }
                try {
                    ep.setStatus(2);
                    ManagerPro mn = new ManagerPro();
                    int check = mn.checkinsertEmpPro(id, n);
                    if (check == 1) {
                        JOptionPane.showMessageDialog(null, "Nhân viên này đã nằm trong dự án không thể thêm lần nữa", "Thông báo", JOptionPane.OK_OPTION);
                    } else {
                        mn.InsertEmpPro(ep);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(frAddEmpforPro.class.getName()).log(Level.SEVERE, null, ex);

                }
            }
            while (dtm2.getRowCount() > 0) {
                dtm2.removeRow(0);
            }
            loadEmPro();
        } catch (SQLException ex) {
            Logger.getLogger(frAddEmpforPro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        int k = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn sửa", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (k == 0) {
            try {
                Project pj = (Project) cboPro.getSelectedItem();
                String n = pj.getId();
                Emp e = (Emp) cboIdEmp.getSelectedItem();
                String id = e.getId();
                EmpPro ep = new EmpPro();
                ep.setIdEmp(id);
                ep.setIdPro(n);
                System.out.println(txtDatejoin.getDate());
                ep.setDateJoin(txtDatejoin.getDate());
                ep.setContent(txtNote.getText());
                if (cboRole.getSelectedIndex() == 0) {
                    ep.setStatus(1);
                }
                ManagerPro mn = new ManagerPro();
                mn.UpdateEmpPro(ep);
                while (dtm2.getRowCount() > 0) {
                    dtm2.removeRow(0);
                }
                loadEmPro();
            } catch (SQLException ex) {
                Logger.getLogger(frAddEmpforPro.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        cboRole.setEnabled(true);
        txtNote.setEnabled(true);
        txtDatejoin.setEnabled(true);
        btnSave.setEnabled(true);
        btnDelete.setEnabled(false);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int k = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa nhân viên khỏi dự án", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (k == 0) {
            try {
                Project pj = (Project) cboPro.getSelectedItem();
                String n = pj.getId();
                Emp e = (Emp) cboIdEmp.getSelectedItem();
                String id = e.getId();
                ManagerPro mn = new ManagerPro();
                mn.DeleteEmpPro(id, n);
                while (dtm2.getRowCount() > 0) {
                    dtm2.removeRow(0);
                }
                loadEmPro();
            } catch (SQLException ex) {
                Logger.getLogger(frAddEmpforPro.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpMouseClicked
        int r = tblEmp.getSelectedRow();
        String n = (String) tblEmp.getValueAt(r, 0);

        for (int j = 0; j <= cboIdEmp.getItemCount(); j++) {
            Emp e = (Emp) cboIdEmp.getItemAt(j);
            String id = e.getId();
            if (id.equalsIgnoreCase(n)) {
                cboIdEmp.setSelectedIndex(j);
                break;
            }
        }
    }//GEN-LAST:event_tblEmpMouseClicked

    private void tblEmpProMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpProMouseClicked
        cboDep.setEnabled(false);
        cboIdEmp.setEnabled(false);
        txtNote.setEnabled(false);
        txtDatejoin.setEnabled(false);
        cboPro.setEnabled(false);
        cboRole.setEnabled(false);
        btnAdd.setEnabled(false);
        btnEdit.setEnabled(true);
        btnDelete.setEnabled(true);
        int r = tblEmpPro.getSelectedRow();
        String n = (String) tblEmpPro.getValueAt(r, 0);
        for (int j = 0; j <= cboIdEmp.getItemCount(); j++) {
            Emp e = (Emp) cboIdEmp.getItemAt(j);
            String id = e.getId();
            if (id.equalsIgnoreCase(n)) {
                cboIdEmp.setSelectedIndex(j);
                break;
            }
        }
        String k = (String) tblEmpPro.getValueAt(r, 1);
        for (int j = 0; j <= cboPro.getItemCount(); j++) {
            Project e = (Project) cboPro.getItemAt(j);
            String id = e.getId();
            if (id.equalsIgnoreCase(k)) {
                cboPro.setSelectedIndex(j);
                break;
            }
        }
        Date da = (Date) tblEmpPro.getValueAt(r, 2);
        txtDatejoin.setDate(da);
        txtNote.setText((String) tblEmpPro.getValueAt(r, 3));
        String a = (String) tblEmpPro.getValueAt(r, 4);
        if (a.equalsIgnoreCase("Leader")) {
            cboRole.setSelectedIndex(1);
        } else {
            cboRole.setSelectedIndex(0);
        }
    }//GEN-LAST:event_tblEmpProMouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtNote.setText("");
        setDate();
        btnAdd.setEnabled(true);
        btnEdit.setEnabled(false);
        btnDelete.setEnabled(false);
        cboDep.setEnabled(true);
        cboIdEmp.setEnabled(true);
        cboPro.setEnabled(true);
        cboRole.setEnabled(true);

    }//GEN-LAST:event_btnResetActionPerformed

    private void tblEmpProPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblEmpProPropertyChange
        try {
            loadEmPro();
        } catch (SQLException ex) {
            Logger.getLogger(frAddEmpforPro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblEmpProPropertyChange

    private void tblEmpPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblEmpPropertyChange
        try {
            loadEmpforPro();
        } catch (SQLException ex) {
            Logger.getLogger(frAddEmpforPro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblEmpPropertyChange
    private void loadDepar() throws SQLException {
        ManagerDeparment mnDepar = new ManagerDeparment();
        Vector<Deparment> lstDepar = mnDepar.getAllDeparment();
        modelDepar = new DefaultComboBoxModel<>(lstDepar);
        cboDep.setModel(modelDepar);

    }

    private void loadcboPro() throws SQLException {
        ManagerPro mn = new ManagerPro();
        Vector<Project> lstDepar = mn.getPro();
        modelPro = new DefaultComboBoxModel<>(lstDepar);

        cboPro.setModel(modelPro);

    }

    private void setcboPro(String id) {
        ComboBoxModel<Project> pv = cboPro.getModel();

        for (int j = 0; j < cboPro.getItemCount(); j++) {
            String n = pv.getElementAt(j).getId();
//            System.out.println(n);
//            String n = pv.getElementAt(j).getIdCity();
            if (id.equalsIgnoreCase(n)) {
                cboPro.setSelectedIndex(j);
            }
        }
    }

    private void loadcboIdE() throws SQLException {
        Deparment dep = (Deparment) cboDep.getSelectedItem();
        String n = dep.getIdDepartment();
        ManagerPro mnDepar = new ManagerPro();
        Vector<ManagerPro.Emp> lstEmp = mnDepar.getEmpforPro(n);
        modelEmp = new DefaultComboBoxModel<>(lstEmp);

        cboIdEmp.setModel(modelEmp);

    }

    private void setDate() {
        Date now = new Date();
        txtDatejoin.setDate(now);

    }

    private void loadEtofr() {
        Emp epx = (Emp) cboIdEmp.getSelectedItem();
        txtNameEmp.setText(epx.getName());
        txtPsEmp.setText(epx.getCv());
        Project p = (Project) cboPro.getSelectedItem();
        txtNamePro.setText(p.getNamePro());

    }

    private void loadEmpforPro() throws SQLException {
        Deparment dep = (Deparment) cboDep.getSelectedItem();
        String n = dep.getIdDepartment();
        ManagerPro mnDepar = new ManagerPro();
        Vector<ManagerPro.Emp> lstEmp = mnDepar.getEmpforPro(n);
        for (int i = 0; i < lstEmp.size(); i++) {
            ManagerPro.Emp elementAt = lstEmp.elementAt(i);
            Vector<String> rowE = new Vector<>();
            rowE.add(elementAt.getId());
            rowE.add(elementAt.getName());
            rowE.add(elementAt.getCv());
            dtm.addRow(rowE);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cboDep;
    private javax.swing.JComboBox cboIdEmp;
    private javax.swing.JComboBox cboPro;
    private javax.swing.JComboBox cboRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblEmp;
    private javax.swing.JTable tblEmpPro;
    private com.toedter.calendar.JDateChooser txtDatejoin;
    private javax.swing.JTextField txtNameEmp;
    private javax.swing.JTextField txtNamePro;
    private javax.swing.JTextArea txtNote;
    private javax.swing.JTextField txtPsEmp;
    // End of variables declaration//GEN-END:variables
}
