/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlns_da;

import Entity.Deparment;
import Mannager.ManagerDeparment;
import Mannager.ManagerDisciplineReward;
import Mannager.ManagerDisciplineReward.EmpDR;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author THUY
 */
public class frEmpDR extends javax.swing.JInternalFrame {

    DefaultComboBoxModel dcbm1, dcbm2, dcbm3;
    DefaultTableModel dtm = new DefaultTableModel();

    /**
     * Creates new form frEmpDR
     */
    public frEmpDR() {
        initComponents();
        dtm.addColumn("Mã nhân viên");
        dtm.addColumn("Mã KTKL");
        dtm.addColumn("Tên nhân viên");
        dtm.addColumn("Chức vụ");
        dtm.addColumn("Ngày KTKL");
        dtm.addColumn("Lý do ");
        dtm.addColumn("Nội dung");
        try {
            loadDepar();
        } catch (SQLException ex) {
            Logger.getLogger(frEmpDR.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            loadEmpDR();
        } catch (SQLException ex) {
            Logger.getLogger(frEmpDR.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblEmpDR.setModel(dtm);
    }

    private void loadEmpDR() throws SQLException {
        Deparment dp = (Deparment) cboDep.getSelectedItem();
        String n = dp.getIdDepartment();
        ManagerDisciplineReward mn = new ManagerDisciplineReward();
        Vector<EmpDR> ls = mn.getEmpDR(n);
        for (int i = 0; i < ls.size(); i++) {
            EmpDR elementAt = ls.elementAt(i);
            Vector row = new Vector();
            row.add(elementAt.getIdemp());
            row.add(elementAt.getId());
            row.add(elementAt.getName());
            row.add(elementAt.getCv());
            row.add(elementAt.getDate());
            row.add(elementAt.getReson());
            row.add(elementAt.getContent());
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpDR = new javax.swing.JTable();
        cboDep = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Danh sách khen thưởng, kỷ luật của nhân viên");

        tblEmpDR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblEmpDR);

        cboDep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Phòng ban:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cboDep, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadDepar() throws SQLException {
        ManagerDeparment mnDepar = new ManagerDeparment();
        Vector<Deparment> lstDepar = mnDepar.getAllDeparment();
        dcbm2 = new DefaultComboBoxModel<>(lstDepar);
        cboDep.setModel(dcbm2);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboDep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmpDR;
    // End of variables declaration//GEN-END:variables
}
