/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlns_da;

import Entity.StatusContract;
import Mannager.MannagerContracts;
import Mannager.MannagerContracts.ListContract;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author THUY
 */
public class frInforContract extends javax.swing.JInternalFrame {
    
    MainFrame parent;
    
    IContract ctr;
    
    DefaultComboBoxModel<StatusContract> dcbm;
    DefaultTableModel model = new DefaultTableModel();
    
    public interface IContract {

        public void Edit(String id);
    }
    
  
    /**
     * Creates new form frInforContract
     */
    public frInforContract() {
        try {
            initComponents();
            model.addColumn("ID");
            model.addColumn("Ngày ký");
            model.addColumn("Hết hạn");
            model.addColumn("Nội dung");
            model.addColumn("Trạng thái");
            model.addColumn("Mã NV");
            model.addColumn("Tên NV");
            loadStatusContract();
            loadContract();
            tblContracts.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(frInforContract.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public frInforContract(MainFrame parent) {
        try {
            initComponents();
            this.ctr = parent;
            model.addColumn("ID");
            model.addColumn("Ngày ký");
            model.addColumn("Hết hạn");
            model.addColumn("Nội dung");
            model.addColumn("Trạng thái");
            model.addColumn("Mã NV");
            model.addColumn("Tên NV");
            loadStatusContract();
            loadContract();
            tblContracts.setModel(model);
            
        } catch (SQLException ex) {
            Logger.getLogger(frInforContract.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        itemSua = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContracts = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtIdContract = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        cboStatus = new javax.swing.JComboBox();

        itemSua.setText("Sửa");
        itemSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSuaActionPerformed(evt);
            }
        });
        jPopupMenu1.add(itemSua);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Danh sách hợp đồng");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblContracts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblContracts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblContractsMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblContracts);

        jLabel1.setText("Loại :");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm theo mã hợp đồng"));

        txtIdContract.setToolTipText("Nhập mã hợp đồng");
        txtIdContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdContractActionPerformed(evt);
            }
        });

        btnSearch.setText("Tìm kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtIdContract, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnSearch)
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdContract, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        cboStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboStatus.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboStatusItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadContract() throws SQLException {
        Mannager.MannagerContracts mn = new MannagerContracts();
        Vector<ListContract> ls = new Vector();
        StatusContract sc = (StatusContract) cboStatus.getSelectedItem();
        int n = sc.getId();
        ls = mn.getListContract(n);
        for (int i = 0; i < ls.size(); i++) {
            ListContract elementAt = ls.elementAt(i);
            Vector<String> row = new Vector<>();
            row.add(elementAt.getId());
            row.add(elementAt.getDateSign());
            row.add(elementAt.getDateEnd());
            row.add(elementAt.getContent());
            row.add(elementAt.getStatus());
            row.add(elementAt.getIdEmp());
            row.add(elementAt.getNameEmp());
            model.addRow(row);
        }
    }
    private void tblContractsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblContractsMouseReleased
        // TODO add your handling code here:
        if (evt.isPopupTrigger()) {
            jPopupMenu1.show(evt.getComponent(), evt.getX(), evt.getY());
            int row = evt.getY() / tblContracts.getRowHeight();
            if (row > -1 && row < tblContracts.getColumnCount()) {
                tblContracts.setRowSelectionInterval(row, row);
                
            } else {
                tblContracts.clearSelection();
            }
        }
    }//GEN-LAST:event_tblContractsMouseReleased
    private void loadStatusContract() throws SQLException {
        MannagerContracts mn = new MannagerContracts();
        Vector<StatusContract> lstDepar = mn.loadStt();
        dcbm = new DefaultComboBoxModel<>(lstDepar);
        cboStatus.setModel(dcbm);
        
    }
    private void txtIdContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdContractActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdContractActionPerformed

    private void cboStatusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboStatusItemStateChanged
        try {
            while (model.getRowCount() > 0) {
                model.removeRow(0);
            }
            loadContract();
        } catch (SQLException ex) {
            Logger.getLogger(frInforContract.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cboStatusItemStateChanged

    private void itemSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSuaActionPerformed
        int r = tblContracts.getSelectedRow();
        String id = (String) tblContracts.getValueAt(r, 0);
        this.ctr.Edit(id);
    }//GEN-LAST:event_itemSuaActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
      
	try {
            // TODO add your handling code here:
            String name = txtIdContract.getText();
            MannagerContracts mn = new MannagerContracts();
            Vector<ListContract> lct = new Vector<>();
            lct = mn.search(name);
            while (model.getRowCount() > 0) {
                model.removeRow(0);
            }
            for (int i = 0; i < lct.size(); i++) {
                ListContract elementAt = lct.elementAt(i);
                Vector<String> ct = new Vector<>();
                ct.add(elementAt.getId());
                ct.add(elementAt.getDateSign());
                ct.add(elementAt.getDateEnd());
                ct.add(elementAt.getContent());
                ct.add(elementAt.getStatus());
                ct.add(elementAt.getIdEmp());
                ct.add(elementAt.getNameEmp());
                model.addRow(ct);
            }
        } catch (SQLException ex) {
            Logger.getLogger(frInforContract.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cboStatus;
    private javax.swing.JMenuItem itemSua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblContracts;
    private javax.swing.JTextField txtIdContract;
    // End of variables declaration//GEN-END:variables
}
