/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlns_da;

import Entity.RankSalary;
import Entity.SalaryBasic;
import Entity.Specialized;
import Mannager.MannagerSalary;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SingleSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AnhHieu
 */
public class frMannagerSalary extends javax.swing.JInternalFrame {

    DefaultTableModel model1 = new DefaultTableModel();
    DefaultTableModel model2 = new DefaultTableModel();
    DefaultTableModel model3 = new DefaultTableModel();

    /**
     * Creates new form frMannagerSalary
     */
    public frMannagerSalary() {
        initComponents();
        try {

            createTbl1();
            createTbl2();
            createTbl3();
            loadSpecial();
            loadcboSpecial();
            loadRank();
            loadSalarybasic();
            tblSpecial.setModel(model1);
            tblRank.setModel(model2);

        } catch (SQLException ex) {
            Logger.getLogger(frMannagerSalary.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblSalaryBasic.setModel(model3);
    }

    private void createTbl1() {

        model1.addColumn("ID");
        model1.addColumn("Ngạch");
    }

    private void createTbl2() {

        model2.addColumn("ID");
        model2.addColumn("Tên bậc");
        model2.addColumn("Hệ số");
    }

    private void createTbl3() {

        model3.addColumn("Mã lương");
        model3.addColumn("Lương cơ bản");
    }

    private void loadSpecial() throws SQLException {
        while (model1.getRowCount() > 0) {
            model1.removeRow(0);
        }
        Vector<Specialized> ls = new Vector<>();
        Mannager.MannagerSalary mn = new MannagerSalary();
        ls = mn.getSpecialized();
        for (int i = 0; i < ls.size(); i++) {
            Specialized elementAt = ls.elementAt(i);
            Vector<String> k = new Vector<>();
            k.add(String.valueOf(elementAt.getId()));
            k.add(String.valueOf(elementAt.getSpecialized()));
            model1.addRow(k);
        }
    }

    private void loadcboSpecial() throws SQLException {
        MannagerSalary mnslr = new MannagerSalary();
        Vector<Specialized> lssp = new Vector<>();
        lssp = mnslr.getSpecialized();
        DefaultComboBoxModel dcbm = new DefaultComboBoxModel(lssp);
        cboSpecial.setModel(dcbm);

    }

    private void loadRank() throws SQLException {
        while (model2.getRowCount() > 0) {
            model2.removeRow(0);
        }
        Specialized spc = (Specialized) cboSpecial.getSelectedItem();
        int i = spc.getId();
        MannagerSalary mnslr = new MannagerSalary();
        Vector<RankSalary> lssp = new Vector<>();
        lssp = mnslr.Rank(i);
        for (int j = 0; j < lssp.size(); j++) {
            RankSalary elementAt = lssp.elementAt(j);
            Vector<String> lz = new Vector<>();
            lz.add(String.valueOf(elementAt.getId()));
            lz.add(String.valueOf(elementAt.getNamerank()));
            lz.add(String.valueOf(elementAt.getCoeffcient()));
            model2.addRow(lz);
        }
    }

    private void loadSalarybasic() throws SQLException {

        MannagerSalary mnslr = new MannagerSalary();
        Vector<SalaryBasic> lssp = new Vector<>();
        lssp = mnslr.Salarybs();
        for (int j = 0; j < lssp.size(); j++) {
            SalaryBasic elementAt = lssp.elementAt(j);
            Vector<String> lz = new Vector<>();
            lz.add(String.valueOf(elementAt.getId()));
            lz.add(String.valueOf(elementAt.getSalaryBasic()));
            model3.addRow(lz);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSpecial = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSpecial = new javax.swing.JTable();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cboSpecial = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtRank = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRank = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCoefficient = new javax.swing.JFormattedTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSalaryBasic = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtSalary = new javax.swing.JFormattedTextField();
        txtId = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Quản lý ngạch bậc lương cơ bản");

        pn3.setToolTipText("");

        jLabel1.setText("Ngạch:");

        tblSpecial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblSpecial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSpecialMouseClicked(evt);
            }
        });
        tblSpecial.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblSpecialPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblSpecial);

        btnEdit.setText("Sửa");
        btnEdit.setEnabled(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Xóa");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jButton11.setText("Reset");

        jButton12.setText("Lưu");
        jButton12.setEnabled(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtSpecial, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSpecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete)
                    .addComponent(btnAdd)
                    .addComponent(jButton11)
                    .addComponent(jButton12))
                .addContainerGap(167, Short.MAX_VALUE))
        );

        pn3.addTab("Ngạch", jPanel1);

        jLabel2.setText("Ngạch:");

        cboSpecial.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboSpecialItemStateChanged(evt);
            }
        });

        jLabel3.setText("Tên bậc:");

        tblRank.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblRank.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRankMouseClicked(evt);
            }
        });
        tblRank.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblRankPropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(tblRank);

        jButton5.setText("Lưu");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setText("Xóa");
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Sửa");
        jButton8.setEnabled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel4.setText("Hệ số:");

        txtCoefficient.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jButton9.setText("Reset");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Thêm");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboSpecial, 0, 167, Short.MAX_VALUE)
                    .addComponent(txtRank))
                .addGap(70, 70, 70)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtCoefficient, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton10)
                .addGap(18, 18, 18)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboSpecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtCoefficient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButton10)
                    .addComponent(jButton7))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pn3.addTab("Xét bậc theo ngạch", jPanel2);

        jLabel5.setText("Mã lương cơ bản:");

        tblSalaryBasic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblSalaryBasic.setToolTipText("");
        tblSalaryBasic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSalaryBasicMouseClicked(evt);
            }
        });
        tblSalaryBasic.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblSalaryBasicPropertyChange(evt);
            }
        });
        jScrollPane3.setViewportView(tblSalaryBasic);

        jLabel6.setText("Lương:");

        txtSalary.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtSalary.setValue(0);

        try {
            txtId.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButton1.setText("Sửa");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Xóa");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Lưu");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Thêm mới");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("Reset");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSalary, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                    .addComponent(txtId))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton2)
                    .addComponent(jButton6))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        pn3.addTab("Xét mức lương cơ bản", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn3, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblSpecialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSpecialMouseClicked
        int k = tblSpecial.getSelectedRow();
        txtSpecial.setText((String) tblSpecial.getValueAt(k, 1));
        btnAdd.setEnabled(false);
        btnEdit.setEnabled(true);
        btnDelete.setEnabled(true);
    }//GEN-LAST:event_tblSpecialMouseClicked

    private void cboSpecialItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboSpecialItemStateChanged
        try {
            int j = tblRank.getRowCount();
            while (model2.getRowCount() > 0) {
                model2.removeRow(0);
            }
            loadRank();
        } catch (SQLException ex) {
            Logger.getLogger(frMannagerSalary.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cboSpecialItemStateChanged

    private void tblSalaryBasicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSalaryBasicMouseClicked
        int k = tblSalaryBasic.getSelectedRow();
        txtId.setText(String.valueOf(tblSalaryBasic.getValueAt(k, 0)));
        txtSalary.setText(String.valueOf(tblSalaryBasic.getValueAt(k, 1)));
        txtId.setEditable(false);
        txtSalary.setEditable(false);
        jButton4.setEnabled(false);
        jButton2.setEnabled(true);
        jButton1.setEnabled(true);

    }//GEN-LAST:event_tblSalaryBasicMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        SalaryBasic sb = new SalaryBasic();
        String id = txtId.getText().trim();
        Float s = Float.valueOf(txtSalary.getValue().toString());
        if (id == null || s == null || "".equals(id)) {
            JOptionPane.showConfirmDialog(null, "Bạn chưa nhập đầy đủ", "Thông báo", JOptionPane.YES_NO_OPTION);
        } else {
            try {
                sb.setId(id);
                sb.setSalaryBasic(Float.parseFloat(txtSalary.getValue().toString()));
                try {
                    MannagerSalary mn = new MannagerSalary();
                    mn.insertRankSalaryBasic(sb);
                    int j = tblSalaryBasic.getRowCount();
                    while (model3.getRowCount() > 0) {
                        model3.removeRow(0);
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(frMannagerSalary.class.getName()).log(Level.SEVERE, null, ex);
                }
                loadSalarybasic();
            } catch (SQLException ex) {
                Logger.getLogger(frMannagerSalary.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jButton3.setEnabled(true);
        txtSalary.setEditable(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        txtId.setEditable(true);
        txtId.setText("");
        txtSalary.setEditable(true);
        txtSalary.setText("");
        jButton4.setEnabled(true);
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Bạn có thật sự muốn xóa", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (x == JOptionPane.YES_OPTION) {

            try {
                String id = txtId.getText().trim();
                MannagerSalary mn = new MannagerSalary();
                mn.deleteRankSalary(id);
                int j = tblSalaryBasic.getRowCount();
                while (model3.getRowCount() > 0) {
                    model3.removeRow(0);
                }
                loadSalarybasic();
            } catch (SQLException ex) {
                Logger.getLogger(frMannagerSalary.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Bạn có thật sự muốn xóa", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (x == JOptionPane.YES_OPTION) {
            try {
                try {
                    int r = tblRank.getSelectedRow();
                    int id = (int) tblRank.getValueAt(r, 0);
                    MannagerSalary mn = new MannagerSalary();
                    mn.deleteRank(id);

                } catch (SQLException ex) {
                    Logger.getLogger(frMannagerSalary.class.getName()).log(Level.SEVERE, null, ex);
                }
                loadRank();
            } catch (SQLException ex) {
                Logger.getLogger(frMannagerSalary.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void tblRankMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRankMouseClicked
        int r = tblRank.getSelectedRow();
        txtRank.setText((String) tblRank.getValueAt(r, 1));
        txtCoefficient.setText((String) tblRank.getValueAt(r, 2));
        txtRank.setEditable(false);
        txtCoefficient.setEditable(false);
        jButton10.setEnabled(false);
        jButton5.setEnabled(false);
        jButton8.setEnabled(true);
        jButton7.setEnabled(true);
    }//GEN-LAST:event_tblRankMouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        txtRank.setEditable(true);
        txtCoefficient.setEditable(true);
        jButton5.setEnabled(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            try {
                int r = tblRank.getSelectedRow();
                int id = (int) tblRank.getValueAt(r, 0);
                RankSalary rs = new RankSalary();
                rs.setId(id);
                Specialized sp = (Specialized) cboSpecial.getSelectedItem();
                int idsp = sp.getId();
                rs.setIdSpecial(idsp);
                rs.setNamerank(txtRank.getText());
                rs.setCoeffcient(Float.parseFloat(txtCoefficient.getValue().toString()));
                MannagerSalary mn = new MannagerSalary();
                mn.updateRank(rs);
            } catch (SQLException ex) {
                Logger.getLogger(frMannagerSalary.class.getName()).log(Level.SEVERE, null, ex);
            }
            loadRank();
        } catch (SQLException ex) {
            Logger.getLogger(frMannagerSalary.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        txtRank.setEditable(true);
        txtCoefficient.setEditable(true);
        jButton5.setEnabled(true);
        jButton10.setEnabled(true);
        txtRank.setText("");
        txtCoefficient.setText("");
        jButton7.setEnabled(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void tblRankPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblRankPropertyChange
        try {
            int j = tblRank.getRowCount();
            while (model2.getRowCount() > 0) {
                model2.removeRow(0);
            }
            loadRank();
        } catch (SQLException ex) {
            Logger.getLogger(frMannagerSalary.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblRankPropertyChange

    private void tblSalaryBasicPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblSalaryBasicPropertyChange
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton4.setEnabled(false);
        try {
            int j = tblSalaryBasic.getRowCount();
            while (model3.getRowCount() > 0) {
                model3.removeRow(0);
            }
            loadSalarybasic();
        } catch (SQLException ex) {
            Logger.getLogger(frMannagerSalary.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblSalaryBasicPropertyChange

    private void tblSpecialPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblSpecialPropertyChange
        try {
            int j = tblSpecial.getRowCount();
            while (model1.getRowCount() > 0) {
                model1.removeRow(0);
            }
            loadSpecial();
        } catch (SQLException ex) {
            Logger.getLogger(frMannagerSalary.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblSpecialPropertyChange

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        jButton12.setEnabled(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            Specialized sb = new Specialized();
            sb.setSpecialized(txtSpecial.getText());
            MannagerSalary mn = new MannagerSalary();
            mn.insetSp(sb);
            loadSpecial();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Thêm mới ko thành công", "Thông báo", JOptionPane.OK_OPTION, new ImageIcon("src/image/k.png"));
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        try {
            try {
                int r = tblSpecial.getSelectedRow();
                int id = (int) tblSpecial.getValueAt(r, 0);

                Specialized sb = new Specialized();
                sb.setId(id);
                sb.setSpecialized(txtSpecial.getText());
                MannagerSalary mn = new MannagerSalary();
                mn.updateSP(sb);

            } catch (SQLException ex) {
              JOptionPane.showMessageDialog(null, "Sửa ko thành công", "Thông báo", JOptionPane.OK_OPTION, new ImageIcon("src/image/k.png"));
            }
            loadSpecial();
        } catch (SQLException ex) {
            Logger.getLogger(frMannagerSalary.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            int x = JOptionPane.showConfirmDialog(null, "Bạn có thật sự muốn xóa", "Thông báo", JOptionPane.YES_NO_OPTION);
        
        if (x == JOptionPane.YES_OPTION) {
            try {
                int r = tblSpecial.getSelectedRow();
                int id = Integer.parseInt((String) tblSpecial.getValueAt(r, 0));
                MannagerSalary mn = new MannagerSalary();
                mn.deleteSp(id);

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Xóa thành công", "Thông báo", JOptionPane.OK_OPTION, new ImageIcon("src/image/k.png"));
            }
        }

        loadSpecial();
    }
    catch (SQLException ex

    
        ) {
            Logger.getLogger(frMannagerSalary.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            try {
                int j = tblSalaryBasic.getRowCount();
                while (model3.getRowCount() > 0) {
                    model3.removeRow(0);
                }
                SalaryBasic sb = new SalaryBasic();
                sb.setId(txtId.getText());
                sb.setSalaryBasic(Float.parseFloat(txtSalary.getValue().toString()));
                MannagerSalary mn = new MannagerSalary();
                mn.updateRankSalaryBasic(sb);
            

} catch (SQLException ex) {
                Logger.getLogger(frMannagerSalary.class
.getName()).log(Level.SEVERE, null, ex);
            }
            loadSalarybasic();
        

} catch (SQLException ex) {
            Logger.getLogger(frMannagerSalary.class
.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try {
            try {
                Specialized spc = (Specialized) cboSpecial.getSelectedItem();
                int id = spc.getId();
                RankSalary rs = new RankSalary();
                rs.setIdSpecial(id);
                rs.setNamerank(txtRank.getText());
                rs.setCoeffcient(Float.parseFloat(txtCoefficient.getText()));
                MannagerSalary mn = new MannagerSalary();
                mn.insertRank(rs);
            

} catch (SQLException ex) {
                Logger.getLogger(frMannagerSalary.class
.getName()).log(Level.SEVERE, null, ex);
            }
            loadRank();
        

} catch (SQLException ex) {
            Logger.getLogger(frMannagerSalary.class
.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton10ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JComboBox<String> cboSpecial;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane pn3;
    private javax.swing.JTable tblRank;
    private javax.swing.JTable tblSalaryBasic;
    private javax.swing.JTable tblSpecial;
    private javax.swing.JFormattedTextField txtCoefficient;
    private javax.swing.JFormattedTextField txtId;
    private javax.swing.JTextField txtRank;
    private javax.swing.JFormattedTextField txtSalary;
    private javax.swing.JTextField txtSpecial;
    // End of variables declaration//GEN-END:variables
}
