/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlns_da;

import Entity.Project;
import Mannager.ManagerPro;
import java.sql.SQLException;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author THUY
 */
public class frProject extends javax.swing.JInternalFrame {

    MainFrame parent;
    IOpenPro iop;
    DefaultTableModel dtm = new DefaultTableModel();

    /**
     * Creates new form frProject
     */
    public interface IOpenPro {

        public void OpenEmpPro(String n);
    }

    public frProject() {
        try {
            initComponents();
            dtm.addColumn("Mã dự án");
            dtm.addColumn("Tên dự án");
            dtm.addColumn("Nội dung");
            dtm.addColumn("Ngày ký kết");
            dtm.addColumn("Ngày bàn giao");
            dtm.addColumn("Giá trị dự án");
            loadPro();
            tblProject.setModel(dtm);
        } catch (SQLException ex) {
            Logger.getLogger(frProject.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public frProject(MainFrame parent) {
        try {
            initComponents();
            dtm.addColumn("Mã dự án");
            dtm.addColumn("Tên dự án");
            dtm.addColumn("Nội dung");
            dtm.addColumn("Ngày ký kết");
            dtm.addColumn("Ngày bàn giao");
            dtm.addColumn("Giá trị dự án");
            this.iop = parent;
            loadPro();
            tblProject.setModel(dtm);
        } catch (SQLException ex) {
            Logger.getLogger(frProject.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        btnViewEmp = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNamePro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDateSign = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtContent = new javax.swing.JTextArea();
        btnSave = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        txtDateDeadline = new com.toedter.calendar.JDateChooser();
        txtValPro = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProject = new javax.swing.JTable();

        jPopupMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPopupMenu1MouseClicked(evt);
            }
        });

        btnViewEmp.setText("Xem nhân viên làm dự án");
        btnViewEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewEmpMouseClicked(evt);
            }
        });
        btnViewEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEmpActionPerformed(evt);
            }
        });
        jPopupMenu1.add(btnViewEmp);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Mã dự án :");

        jLabel2.setText("Tên dự án :");

        jLabel3.setText("Ngày nhận :");

        txtDateSign.setDateFormatString("yyyy-MM-dd");

        jLabel4.setText("Ngày bàn giao :");

        jLabel5.setText("Giá trị dự án :");

        jLabel6.setText("Nội dung dự án :");

        txtContent.setColumns(20);
        txtContent.setRows(5);
        jScrollPane1.setViewportView(txtContent);

        btnSave.setText("Lưu");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnReset.setText("Làm lại");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnDelete.setText("Xóa");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnEdit.setText("Sửa");
        btnEdit.setEnabled(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        txtDateDeadline.setDateFormatString("yyyy-MM-dd");

        txtValPro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDateSign, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtNamePro, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDateDeadline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtValPro))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 246, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNamePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtDateSign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtDateDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtValPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnReset)
                    .addComponent(btnSave)
                    .addComponent(btnEdit)
                    .addComponent(btnAdd))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tblProject.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProjectMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblProjectMouseReleased(evt);
            }
        });
        tblProject.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblProjectPropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(tblProject);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void loadPro() throws SQLException {
        ManagerPro mn = new ManagerPro();
        Vector<Project> ls = new Vector<>();
        ls = mn.getPro();
        for (int i = 0; i < ls.size(); i++) {
            Project elementAt = ls.elementAt(i);
            Vector row = new Vector<>();
            row.add(elementAt.getId());
            row.add(elementAt.getNamePro());
            row.add(elementAt.getContentPro());
            row.add(elementAt.getDateSign());
            row.add(elementAt.getDateDeadline());
            row.add(String.valueOf(elementAt.getValPro()));
            dtm.addRow(row);
        }

    }
    private void tblProjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProjectMouseClicked
        btnAdd.setEnabled(false);
        btnEdit.setEnabled(true);
        btnDelete.setEnabled(true);
        int r = tblProject.getSelectedRow();
        txtId.setText((String) tblProject.getValueAt(r, 0));
        txtNamePro.setText((String) tblProject.getValueAt(r, 1));
        txtContent.setText((String) tblProject.getValueAt(r, 2));
        txtDateSign.setDate((Date) tblProject.getValueAt(r, 3));
        txtDateDeadline.setDate((Date) tblProject.getValueAt(r, 4));
        txtValPro.setText(String.valueOf(tblProject.getValueAt(r, 5)));
        txtId.setEditable(false);
        txtNamePro.setEditable(false);
        txtContent.setEditable(false);
        txtDateSign.setEnabled(false);
        txtDateDeadline.setEnabled(false);
        txtValPro.setEditable(false);
    }//GEN-LAST:event_tblProjectMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        txtId.setEditable(false);
        txtNamePro.setEditable(true);
        txtContent.setEditable(true);
        txtDateSign.setEnabled(true);
        txtDateDeadline.setEnabled(true);
        txtValPro.setEditable(true);
        btnSave.setEnabled(true);
        btnDelete.setEnabled(false);
        btnAdd.setEnabled(true);
        btnEdit.setEnabled(false);
        btnDelete.setEnabled(false);
        btnSave.setEnabled(true);

    }//GEN-LAST:event_btnEditActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtId.setEditable(true);
        txtNamePro.setEditable(true);
        txtContent.setEditable(true);
        txtDateSign.setEnabled(true);
        txtDateDeadline.setEnabled(true);
        txtValPro.setEditable(true);
        txtId.setText("");
        txtNamePro.setText("");
        txtContent.setText("");
        Date now = new Date();
        txtDateSign.setDate(now);
        txtDateDeadline.setDate(now);
        txtValPro.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (txtId.getText().equals("") || txtNamePro.getText().equals("") || txtContent.getText().equals("") || txtValPro.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Cần nhập thông tin đầy đủ trước khi thêm", "Thông báo", JOptionPane.ABORT);
        } else {
            try {
                Project pj = new Project();
                pj.setId(txtId.getText());
                pj.setNamePro(txtNamePro.getText());
                pj.setDateSign(txtDateSign.getDate());
                pj.setDateDeadline(txtDateDeadline.getDate());
                pj.setContentPro(txtContent.getText()); 
                System.out.println(txtValPro.getText());
                pj.setValPro(Float.parseFloat(txtValPro.getText()));
               
                ManagerPro mn = new ManagerPro();
                int check = mn.checkinsertPro(txtId.getText());
                if (check == 1) {
                    JOptionPane.showConfirmDialog(null, "Không thể thêm ID Project bị trùng", "Thông báo", JOptionPane.OK_OPTION);
                } else {
                    mn.InsertPro(pj);
                    while (dtm.getRowCount() > 0) {
                        dtm.removeRow(0);
                    }
                    loadPro();
                }
            } catch (SQLException ex) {
                Logger.getLogger(frProject.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (txtId.getText().equals("") || txtNamePro.getText().equals("") || txtContent.getText().equals("") || txtValPro.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Cần nhập thông tin đầy đủ trước khi lưu", "Thông báo", JOptionPane.ABORT);
        } else {
            try {
                Project pj = new Project();
                pj.setId(txtId.getText());
                pj.setNamePro(txtNamePro.getText());
                pj.setDateSign(txtDateSign.getDate());
                pj.setDateDeadline(txtDateDeadline.getDate());
                pj.setContentPro(txtContent.getText());
                pj.setValPro(Float.parseFloat(txtValPro.getText()));
                ManagerPro mn = new ManagerPro();
                mn.UpdatePro(pj);
                while (dtm.getRowCount() > 0) {
                    dtm.removeRow(0);
                }
                loadPro();
            } catch (SQLException ex) {
                Logger.getLogger(frProject.class.getName()).log(Level.SEVERE, null, ex);

            }

        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int k = JOptionPane.showConfirmDialog(null, "Bạn thật sự muốn xóa", "Thông báo", JOptionPane.OK_CANCEL_OPTION);
        ManagerPro mn = new ManagerPro();
        String n = txtId.getText();
        if (k == JOptionPane.OK_OPTION) {
            try {
                try {

                    int check = mn.checkDeletePro(n);
                    if (check == 1) {
                        JOptionPane.showMessageDialog(null, "Dự án vẫn còn nhân viên đề nghị loại nhân viên khỏi dự án trước khi xóa", "Thông báo", JOptionPane.OK_OPTION);
                    } else {
                        mn.DeletePro(n);

                    }
                } catch (SQLException ex) {
                    Logger.getLogger(frProject.class
                            .getName()).log(Level.SEVERE, null, ex);
                }
                while (dtm.getRowCount() > 0) {
                    dtm.removeRow(0);
                }
                loadPro();

            } catch (SQLException ex) {
                Logger.getLogger(frProject.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnViewEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewEmpMouseClicked

    }//GEN-LAST:event_btnViewEmpMouseClicked

    private void tblProjectMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProjectMouseReleased
        if (evt.isPopupTrigger()) {
            jPopupMenu1.show(evt.getComponent(), evt.getX(), evt.getY());
            int row = evt.getY() / tblProject.getRowHeight();
            if (row > -1 && row < tblProject.getColumnCount()) {
                tblProject.setRowSelectionInterval(row, row);

            } else {
                tblProject.clearSelection();
            }
        }
    }//GEN-LAST:event_tblProjectMouseReleased

    private void jPopupMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPopupMenu1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPopupMenu1MouseClicked

    private void btnViewEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEmpActionPerformed
        int r = tblProject.getSelectedRow();
        String n = (String) tblProject.getValueAt(r, 0);
        this.iop.OpenEmpPro(n);
    }//GEN-LAST:event_btnViewEmpActionPerformed

    private void tblProjectPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblProjectPropertyChange
        try {
            loadPro();

        } catch (SQLException ex) {
            Logger.getLogger(frProject.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblProjectPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JMenuItem btnViewEmp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblProject;
    private javax.swing.JTextArea txtContent;
    private com.toedter.calendar.JDateChooser txtDateDeadline;
    private com.toedter.calendar.JDateChooser txtDateSign;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNamePro;
    private javax.swing.JFormattedTextField txtValPro;
    // End of variables declaration//GEN-END:variables
}
