/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlns_da;

import Entity.Deparment;
import Mannager.ManagerDeparment;
import Mannager.ManagerReport;
import Mannager.ManagerReport.LevelRP;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.chart.plot.Plot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author AnhHieu
 */
public class frRepostLevel extends javax.swing.JInternalFrame {

    /**
     * Creates new form frRepostLevel
     */
    public frRepostLevel() {
        initComponents();
        try {
            loadDeparment();
        } catch (SQLException ex) {
            Logger.getLogger(frRepostLevel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    DefaultComboBoxModel<Deparment> modelDeparment;

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboDeparment = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setClosable(true);
        setTitle("Thống kê trình độ nhân viên");

        cboDeparment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Phòng ban:");

        jButton1.setText("Thống kê");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboDeparment, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 380, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboDeparment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void loadDeparment() throws SQLException {
        ManagerDeparment mnDeparment = new ManagerDeparment();
        Vector<Deparment> lstDepar = mnDeparment.getAllDeparment();
        modelDeparment = new DefaultComboBoxModel<>(lstDepar);
        cboDeparment.setModel(modelDeparment);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Deparment dp = (Deparment) cboDeparment.getSelectedItem();
            String n = dp.getIdDepartment();
            int s1 = 0;
            int s2 = 0;
            int s3 = 0;
            int s4 = 0;
            int s5 = 0;
            DefaultCategoryDataset dataset = new DefaultCategoryDataset();

            Mannager.ManagerReport mn = new ManagerReport();
            Vector<LevelRP> ls = mn.getEmpforPro(n);
            dataset.setValue(s1, "", "Tiến sĩ");
            dataset.setValue(s2, "", "Thạc sĩ");
            dataset.setValue(s3, "", "Đại Học");
            dataset.setValue(s4, "", "Cao Đẳng");
            dataset.setValue(s5, "", "Trung Cấp Nghề");
            for (int i = 0; i < ls.size(); i++) {
                LevelRP elementAt = ls.elementAt(i);

                if (elementAt.getName().equalsIgnoreCase("Tiến Sĩ")) {
                    s1 = elementAt.getCount();
                    dataset.setValue(s1, "", "Tiến sĩ");
                } else if (elementAt.getName().equalsIgnoreCase("Thạc sĩ")) {
                    s2 = elementAt.getCount();
                    dataset.setValue(s2, "", "Thạc sĩ");
                } else if (elementAt.getName().equalsIgnoreCase("Đại Học")) {
                    s3 = elementAt.getCount();
                    dataset.setValue(s3, "", "Đại Học");
                } else if (elementAt.getName().equalsIgnoreCase("Cao Đẳng")) {
                    s4 = elementAt.getCount();
                    dataset.setValue(s4, "", "Cao Đẳng");
                } else if (elementAt.getName().equalsIgnoreCase("Trung Cấp Nghề")) {
                    s5 = elementAt.getCount();
                    dataset.setValue(s5, "", "Trung Cấp Nghề");
                } else {
                    dataset.setValue(new Integer(elementAt.getCount()), "", elementAt.getName());

                }
            }
            JFreeChart chart = ChartFactory.createBarChart("", "", "", dataset, PlotOrientation.HORIZONTAL, false, false, false);
            CategoryPlot catPlot = chart.getCategoryPlot();
            catPlot.setRangeGridlinePaint(Color.BLACK);
            ChartPanel frame = new ChartPanel(chart);
            jPanel1.removeAll();
            jPanel1.add(frame, BorderLayout.CENTER);
            jPanel1.validate();
        } catch (SQLException ex) {
            Logger.getLogger(frRepostLevel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboDeparment;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
