/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlns_da;

import Entity.Department;
import Mannager.MannagerPayroll;
import Mannager.MannagerPayroll.Payrolls;
import Mannager.MannagergetData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AnhHieu
 */
public class frRepostSalaryEmp extends javax.swing.JInternalFrame {

    DefaultTableModel model = new DefaultTableModel();
    DefaultComboBoxModel dcbm;
    DefaultComboBoxModel dcbmz;

    /**
     * Creates new form frRepostSalaryEmp
     */
    public frRepostSalaryEmp() {
        try {
            initComponents();
            model.addColumn("Mã nhân viên");
            model.addColumn("Tên nhân viên");
            model.addColumn("Số công");
            model.addColumn("Rank lương");
            model.addColumn("Lương cơ bản");
            model.addColumn("Tổng lương");
            loadDep();
            loadM();

        } catch (SQLException ex) {
            Logger.getLogger(frRepostSalaryEmp.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            loadPayroll();
        } catch (SQLException ex) {
            Logger.getLogger(frRepostSalaryEmp.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblEmp.setModel(model);
    }

    private void loadDep() throws SQLException {
        MannagergetData mnd = new MannagergetData();
        Vector<Department> lst = mnd.getDepart();
        dcbm = new DefaultComboBoxModel<>(lst);
        cboDep.setModel(dcbm);
    }

    private void loadM() throws SQLException {
        Mannager.MannagerPayroll mnd = new MannagerPayroll();
        Vector lst = mnd.getMonth();
        dcbmz = new DefaultComboBoxModel<>(lst);
        cboMonth.setModel(dcbmz);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cboDep = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtIdEmp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        cboMonth = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmp = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Kiểm tra lương tháng");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Check"));

        cboDep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboDep.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboDepItemStateChanged(evt);
            }
        });

        jLabel1.setText("Phòng ban:");

        jLabel2.setText("Mã NV:");

        btnSearch.setText("Tìm kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        cboMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboMonth.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboMonthItemStateChanged(evt);
            }
        });

        jLabel3.setText("Tháng:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboMonth, 0, 170, Short.MAX_VALUE)
                    .addComponent(cboDep, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(txtIdEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)))
        );

        tblEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblEmp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void loadPayroll() throws SQLException {
        Department dp = (Department) cboDep.getSelectedItem();
        String n = dp.getId();
        String c = cboMonth.getSelectedItem().toString();
        System.out.println(n);
        System.out.println(c);
        MannagerPayroll mn = new MannagerPayroll();
        Vector<Payrolls> ls = mn.getAll(n, c);
        if (ls.size() == 0) {
            JOptionPane.showMessageDialog(null, "Không có nhân viên nào có lương", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            for (int i = 0; i < ls.size(); i++) {
                Payrolls elementAt = ls.elementAt(i);
                Vector row = new Vector<>();
                row.add(elementAt.getIdEmp());
                row.add(elementAt.getName());
                row.add(elementAt.getCount());
                row.add(elementAt.getRank());
                row.add(elementAt.getSalary());
                row.add(elementAt.getTotal());
                model.addRow(row);
            }

        }
    }

    private void searchEmp() throws SQLException {
        Department dp = (Department) cboDep.getSelectedItem();
        String n = dp.getId();
        String c = cboMonth.getSelectedItem().toString();
        String id = txtIdEmp.getText();
        System.out.println(n);
        System.out.println(c);
        MannagerPayroll mn = new MannagerPayroll();
        Vector<Payrolls> ls = mn.getEmp(n, c, id);
        if (ls.size() == 0) {
            JOptionPane.showMessageDialog(null, "Không tìm thấy nhân viên có mã "+id+"trong phòng ban này hoặc không có lương tháng "+c, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            for (int i = 0; i < ls.size(); i++) {
                Payrolls elementAt = ls.elementAt(i);
                Vector row = new Vector<>();
                row.add(elementAt.getIdEmp());
                row.add(elementAt.getName());
                row.add(elementAt.getCount());
                row.add(elementAt.getRank());
                row.add(elementAt.getSalary());
                row.add(elementAt.getTotal());
                model.addRow(row);
            }

        }
    }

    private void cboDepItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboDepItemStateChanged
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        try {
            loadPayroll();
        } catch (SQLException ex) {
            Logger.getLogger(frRepostSalaryEmp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cboDepItemStateChanged

    private void cboMonthItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboMonthItemStateChanged
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        try {
            loadPayroll();
        } catch (SQLException ex) {
            Logger.getLogger(frRepostSalaryEmp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cboMonthItemStateChanged

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        try {
            searchEmp();
        } catch (SQLException ex) {
            Logger.getLogger(frRepostSalaryEmp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cboDep;
    private javax.swing.JComboBox<String> cboMonth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmp;
    private javax.swing.JTextField txtIdEmp;
    // End of variables declaration//GEN-END:variables
}
